//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HDATAContext : DbContext
    {
        public HDATAContext()
            : base("name=HDATAContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apresentacao_produto> apresentacao_produto { get; set; }
        public virtual DbSet<caixa> caixas { get; set; }
        public virtual DbSet<categoria_produto> categoria_produto { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<condicao_pagamento> condicao_pagamento { get; set; }
        public virtual DbSet<custo> custoes { get; set; }
        public virtual DbSet<disciplina_estoque> disciplina_estoque { get; set; }
        public virtual DbSet<elementos_promocao> elementos_promocao { get; set; }
        public virtual DbSet<estoque_produto> estoque_produto { get; set; }
        public virtual DbSet<forma_pagamento> forma_pagamento { get; set; }
        public virtual DbSet<fornecedor> fornecedors { get; set; }
        public virtual DbSet<item_reserva> item_reserva { get; set; }
        public virtual DbSet<item_venda> item_venda { get; set; }
        public virtual DbSet<local_estoque> local_estoque { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<lote> lotes { get; set; }
        public virtual DbSet<movimento_caixa> movimento_caixa { get; set; }
        public virtual DbSet<movimento_estoque> movimento_estoque { get; set; }
        public virtual DbSet<permissao> permissaos { get; set; }
        public virtual DbSet<produto> produtoes { get; set; }
        public virtual DbSet<promocao> promocaos { get; set; }
        public virtual DbSet<reserva> reservas { get; set; }
        public virtual DbSet<tipo_custo> tipo_custo { get; set; }
        public virtual DbSet<tipo_doc_venda> tipo_doc_venda { get; set; }
        public virtual DbSet<tipo_log> tipo_log { get; set; }
        public virtual DbSet<tipo_movimento> tipo_movimento { get; set; }
        public virtual DbSet<tipo_produto> tipo_produto { get; set; }
        public virtual DbSet<tipo_reserva> tipo_reserva { get; set; }
        public virtual DbSet<tipo_unidade> tipo_unidade { get; set; }
        public virtual DbSet<tipo_utilizador> tipo_utilizador { get; set; }
        public virtual DbSet<utilizador> utilizadors { get; set; }
        public virtual DbSet<venda> vendas { get; set; }
        public virtual DbSet<venda_forma_pagamento> venda_forma_pagamento { get; set; }
    }
}
