//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class caixa
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public caixa()
    {
        this.vendas = new HashSet<venda>();
        this.movimento_caixa = new HashSet<movimento_caixa>();
    }

    public int id_caixa { get; set; }
    public int id_utilizador { get; set; }
    public System.DateTime data_abertura { get; set; }
    public Nullable<System.DateTime> data_fecho { get; set; }
    public double valor_inicial { get; set; }
    public double valor_actual { get; set; }
    public double saldo { get; set; }
    public string estado_caixa { get; set; }
    public Nullable<System.DateTime> data_actualizacao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<venda> vendas { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<movimento_caixa> movimento_caixa { get; set; }
    public virtual utilizador utilizador { get; set; }
}
