//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class cliente
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public cliente()
    {
        this.vendas = new HashSet<venda>();
        this.reservas = new HashSet<reserva>();
    }

    public int id_cliente { get; set; }
    public string nome { get; set; }
    public string bi { get; set; }
    public string telefone { get; set; }
    public string email { get; set; }
    public string endereco { get; set; }
    public Nullable<System.DateTime> data_cadastro { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<venda> vendas { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<reserva> reservas { get; set; }
}
