//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class custo
{
    public int id_custo { get; set; }
    public string descricao { get; set; }
    public System.DateTime data_gasto { get; set; }
    public double valor { get; set; }
    public string razao { get; set; }
    public string notas { get; set; }
    public Nullable<int> status { get; set; }
    public int id_tipo_custo { get; set; }
    public int id_utilizador { get; set; }

    public virtual tipo_custo tipo_custo { get; set; }
    public virtual utilizador utilizador { get; set; }
}
