//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class estoque_produto
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public estoque_produto()
    {
        this.movimento_estoque = new HashSet<movimento_estoque>();
    }

    public int id_local_estoque { get; set; }
    public int id_lote { get; set; }
    public int id_produto { get; set; }
    public int qtd_encomenda { get; set; }
    public Nullable<int> qtd_existente { get; set; }
    public int qtd_minima { get; set; }
    public System.DateTime data_criacao { get; set; }
    public double preco_venda { get; set; }
    public Nullable<int> status { get; set; }
    public int id_user { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<movimento_estoque> movimento_estoque { get; set; }
    public virtual local_estoque local_estoque { get; set; }
    public virtual lote lote { get; set; }
    public virtual utilizador utilizador { get; set; }
}
