//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class fornecedor
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public fornecedor()
    {
        this.lotes = new HashSet<lote>();
    }

    public int id_fornecedor { get; set; }
    public string nome { get; set; }
    public string nif { get; set; }
    public string endereco { get; set; }
    public string telefone { get; set; }
    public string email { get; set; }
    public string detalhe { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<System.DateTime> data_cadastro { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<lote> lotes { get; set; }
}
