//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class item_reserva
{
    public int id_lote { get; set; }
    public int id_produto { get; set; }
    public int id_reserva { get; set; }
    public int quant_reservada_mensal { get; set; }
    public int quant_levantada { get; set; }
    public int unid_levantamento { get; set; }
    public int status { get; set; }

    public virtual lote lote { get; set; }
    public virtual reserva reserva { get; set; }
}
