//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class local_estoque
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public local_estoque()
    {
        this.estoque_produto = new HashSet<estoque_produto>();
    }

    public int id_local_estoque { get; set; }
    public string descricao { get; set; }
    public string estado_local_estoque { get; set; }
    public string operacao { get; set; }
    public string endereco { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<estoque_produto> estoque_produto { get; set; }
}
