//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class lote
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public lote()
    {
        this.elementos_promocao = new HashSet<elementos_promocao>();
        this.estoque_produto = new HashSet<estoque_produto>();
        this.item_reserva = new HashSet<item_reserva>();
        this.item_venda = new HashSet<item_venda>();
    }

    public int id_lote { get; set; }
    public int id_produto { get; set; }
    public int id_fornecedor { get; set; }
    public int id_apresentacao_produto { get; set; }
    public string descricao { get; set; }
    public System.DateTime data_validade { get; set; }
    public string info_lote { get; set; }
    public string codigo_barra { get; set; }
    public string referencia { get; set; }
    public Nullable<double> margem_venda { get; set; }
    public Nullable<double> preco_compra { get; set; }
    public Nullable<double> preco_venda { get; set; }
    public Nullable<System.DateTime> data_cadastro { get; set; }
    public System.DateTime data_alteracao { get; set; }
    public Nullable<int> status { get; set; }

    public virtual apresentacao_produto apresentacao_produto { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<elementos_promocao> elementos_promocao { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<estoque_produto> estoque_produto { get; set; }
    public virtual fornecedor fornecedor { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<item_reserva> item_reserva { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<item_venda> item_venda { get; set; }
    public virtual produto produto { get; set; }
}
