//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class movimento_estoque
{
    public int id_movimento_estoque { get; set; }
    public Nullable<System.DateTime> data { get; set; }
    public Nullable<System.DateTime> data_compra { get; set; }
    public Nullable<float> preco_compra { get; set; }
    public Nullable<int> qtd { get; set; }
    public string descricao { get; set; }
    public Nullable<int> ajuste { get; set; }
    public int id_tipo_movimento { get; set; }
    public int id_local_estoque { get; set; }
    public int id_lote { get; set; }
    public int id_produto { get; set; }
    public int id_utilizador { get; set; }

    public virtual estoque_produto estoque_produto { get; set; }
    public virtual tipo_movimento tipo_movimento { get; set; }
    public virtual utilizador utilizador { get; set; }
}
