//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class produto
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public produto()
    {
        this.lotes = new HashSet<lote>();
    }

    public int id_produto { get; set; }
    public string nome { get; set; }
    public string codigo_barra { get; set; }
    public string descricao { get; set; }
    public System.DateTime data_alteracao { get; set; }
    public int id_categoria { get; set; }
    public Nullable<int> status { get; set; }
    public int id_tipo_unidade { get; set; }
    public Nullable<int> id_disciplina_estoque { get; set; }
    public int id_tipo_produto { get; set; }

    public virtual categoria_produto categoria_produto { get; set; }
    public virtual disciplina_estoque disciplina_estoque { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<lote> lotes { get; set; }
    public virtual tipo_produto tipo_produto { get; set; }
    public virtual tipo_unidade tipo_unidade { get; set; }
}
