//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class promocao
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public promocao()
    {
        this.elementos_promocao = new HashSet<elementos_promocao>();
    }

    public int id_promocao { get; set; }
    public Nullable<System.DateTime> data_inicio { get; set; }
    public Nullable<System.DateTime> data_fim { get; set; }
    public string nome { get; set; }
    public Nullable<int> status { get; set; }
    public string descricao { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<elementos_promocao> elementos_promocao { get; set; }
}
