//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class reserva
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public reserva()
    {
        this.item_reserva = new HashSet<item_reserva>();
        this.vendas = new HashSet<venda>();
    }

    public int id_reserva { get; set; }
    public int id_cliente { get; set; }
    public int id_user { get; set; }
    public int status { get; set; }
    public Nullable<System.DateTime> data_inicio { get; set; }
    public Nullable<System.DateTime> data_fim { get; set; }
    public int id_tipo_reserva { get; set; }

    public virtual cliente cliente { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<item_reserva> item_reserva { get; set; }
    public virtual tipo_reserva tipo_reserva { get; set; }
    public virtual utilizador utilizador { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<venda> vendas { get; set; }
}
