//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class venda
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public venda()
    {
        this.item_venda = new HashSet<item_venda>();
        this.venda_forma_pagamento = new HashSet<venda_forma_pagamento>();
        this.reservas = new HashSet<reserva>();
    }

    public int id_venda { get; set; }
    public int id_cliente { get; set; }
    public int id_utilizador { get; set; }
    public int id_tipo_documento { get; set; }
    public int id_condicao_pagamento { get; set; }
    public int id_caixa { get; set; }
    public System.DateTime data_venda { get; set; }
    public string descricao { get; set; }
    public double total_venda { get; set; }
    public double valor_pago { get; set; }
    public double toco { get; set; }
    public int num_doc { get; set; }
    public string notas { get; set; }
    public Nullable<int> status { get; set; }
    public System.DateTime data_cadastro { get; set; }
    public System.DateTime data_actualizacao { get; set; }

    public virtual caixa caixa { get; set; }
    public virtual cliente cliente { get; set; }
    public virtual condicao_pagamento condicao_pagamento { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<item_venda> item_venda { get; set; }
    public virtual tipo_doc_venda tipo_doc_venda { get; set; }
    public virtual utilizador utilizador { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<venda_forma_pagamento> venda_forma_pagamento { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<reserva> reservas { get; set; }
}
