//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class venda_forma_pagamento
{
    public int id_venda { get; set; }
    public int id_forma_pagamento { get; set; }
    public Nullable<double> valor_pago { get; set; }
    public string referencia { get; set; }

    public virtual forma_pagamento forma_pagamento { get; set; }
    public virtual venda venda { get; set; }
}
